import { ThemeProvider } from '@/components/mode-toggle/theme-provider'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import { cookies } from 'next/headers'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import { NotificationProvider } from '../components/notification/NotificationProvider'
import NotificationStack from '../components/notification'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true'
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />

            <SidebarTrigger className="p-3 ml-2 mt-6.5" />

            <NotificationProvider>
              {children}
              <NotificationStack />
            </NotificationProvider>
          </SidebarProvider>
        </ThemeProvider>
        <div />
      </body>
    </html>
  )
}
