"""change

Revision ID: 2315954b6fe7
Revises: 8adec6f203e9
Create Date: 2025-09-28 11:40:33.792663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2315954b6fe7'
down_revision: Union[str, None] = '8adec6f203e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('institution_id', sa.String(length=64), nullable=True))
    op.add_column('accounts', sa.Column('institution_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_accounts_institution_id'), 'accounts', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_institution_id'), table_name='accounts')
    op.drop_column('accounts', 'institution_name')
    op.drop_column('accounts', 'institution_id')
    # ### end Alembic commands ###
