"""change

Revision ID: 2322584b0e42
Revises: 1251b528e0ba
Create Date: 2025-09-28 15:39:29.206782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2322584b0e42'
down_revision: Union[str, None] = '1251b528e0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_items', sa.Column('transactions_cursor', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_connection_items_transactions_cursor'), 'connection_items', ['transactions_cursor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_items_transactions_cursor'), table_name='connection_items')
    op.drop_column('connection_items', 'transactions_cursor')
    # ### end Alembic commands ###
