"""change

Revision ID: 5c598df205a0
Revises: a27cc23becdb
Create Date: 2025-10-30 14:24:09.452013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c598df205a0'
down_revision: Union[str, None] = 'a27cc23becdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('group', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'group')
    # ### end Alembic commands ###
