"""change

Revision ID: 8adec6f203e9
Revises: 93a83b54aff8
Create Date: 2025-09-25 22:06:51.509034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adec6f203e9'
down_revision: Union[str, None] = '93a83b54aff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_items', sa.Column('institution_id', sa.String(length=64), nullable=True))
    op.add_column('connection_items', sa.Column('institution_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_connection_items_institution_id'), 'connection_items', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_items_institution_id'), table_name='connection_items')
    op.drop_column('connection_items', 'institution_name')
    op.drop_column('connection_items', 'institution_id')
    # ### end Alembic commands ###
