"""change

Revision ID: a27cc23becdb
Revises: 019de0063aab
Create Date: 2025-10-30 12:39:58.225098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27cc23becdb'
down_revision: Union[str, None] = '019de0063aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('allotted_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_budget_category_user_name')
    )
    op.create_index(op.f('ix_budget_categories_user_id'), 'budget_categories', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_budget_category_id'), 'transactions', ['budget_category_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'budget_categories', ['budget_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_budget_category_id'), table_name='transactions')
    op.drop_column('transactions', 'budget_category_id')
    op.drop_index(op.f('ix_budget_categories_user_id'), table_name='budget_categories')
    op.drop_table('budget_categories')
    # ### end Alembic commands ###
