"""change

Revision ID: ae346dea0042
Revises: 17b909357ae9
Create Date: 2025-09-20 14:19:46.909473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae346dea0042'
down_revision: Union[str, None] = '17b909357ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=128), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_items_plaid_item_id'), 'connection_items', ['plaid_item_id'], unique=True)
    op.create_index(op.f('ix_connection_items_user_id'), 'connection_items', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['connection_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id', name='uq_accounts_plaid_account_id')
    )
    op.create_index('ix_accounts_item_id', 'accounts', ['item_id'], unique=False)
    op.create_index(op.f('ix_accounts_plaid_account_id'), 'accounts', ['plaid_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_plaid_account_id'), table_name='accounts')
    op.drop_index('ix_accounts_item_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_connection_items_user_id'), table_name='connection_items')
    op.drop_index(op.f('ix_connection_items_plaid_item_id'), table_name='connection_items')
    op.drop_table('connection_items')
    # ### end Alembic commands ###
