from typing import Protocol, Sequence, Optional
from app.domain.entities import UserEntity


# DB Repositories Interfaces


# need to use protocol so anything with same methods counts as class for testing purposes
class UserRepo(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[UserEntity]: ...
    async def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    async def list(self) -> Sequence[UserEntity]: ...
    async def add(self, user: UserEntity) -> UserEntity: ...
    async def delete(self, user_id: int) -> None: ...